version: '3.8'
networks:
  default:
    driver: bridge
services:
  php-app:
    build: .
    container_name: php-app
    image: ngogiaphong123/ci_demo_probation
    restart: always
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - default

  mysql:
    image: mysql
    restart: always
    env_file:
      - .env.docker
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Test
      - MYSQL_USER=giaphong
      - MYSQL_PASSWORD=phongjasmine123
      - MYSQL_PORT=3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
