version: '1'
services:
  mysql:
    image: mysql:8.1.0
    ports:
      - "13306:3306"
    environment:
      DB_HOST: mysql
      MYSQL_DATABASE: Test
      MYSQL_USER: giaphong
      MYSQL_PASSWORD: phongjasmine123
      MYSQL_ROOT_PASSWORD: phongjasmine123
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - php_network

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    restart: always
    working_dir: /var/www/  
    volumes:
      - ../:/var/www
    networks:
      - php_network

  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d

networks:
  php_network:
    driver: bridge
